apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: app
          image: wlgns5376/docker-image:0.0.1
          ports:
            - name: phpfpm
              containerPort: 9000
              protocol: TCP              
